/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Variant__3 = IDL.Variant({
  'Secunderabad' : IDL.Null,
  'Cyberabad' : IDL.Null,
  'Rangareddy' : IDL.Null,
  'Hyderabad' : IDL.Null,
});
export const Variant__1 = IDL.Variant({
  'startupLaw' : IDL.Null,
  'employmentLaw' : IDL.Null,
  'corporateLaw' : IDL.Null,
  'taxLaw' : IDL.Null,
  'documentationServices' : IDL.Null,
  'propertyLaw' : IDL.Null,
  'ipLaw' : IDL.Null,
  'civilLitigation' : IDL.Null,
  'criminalDefense' : IDL.Null,
  'familyLaw' : IDL.Null,
});
export const LegalListing = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'jurisdiction' : Variant__3,
  'specialization' : Variant__1,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateContactFormSubmissionInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'jurisdiction' : Variant__3,
  'message' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Text,
});
export const Variant__2 = IDL.Variant({
  'national' : IDL.Null,
  'local' : IDL.Null,
});
export const Variant = IDL.Variant({
  'new' : IDL.Null,
  'resolved' : IDL.Null,
  'contacted' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactFormSubmission = IDL.Record({
  'id' : IDL.Nat,
  'status' : Variant,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'jurisdiction' : Variant__3,
  'message' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'phoneNumber' : IDL.Text,
});
export const ServiceDetails = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'practiceArea' : Variant__1,
  'jurisdiction' : Variant__3,
  'keywords' : IDL.Vec(IDL.Text),
});
export const TrendingTopic = IDL.Record({
  'id' : IDL.Nat,
  'popularityScore' : IDL.Nat,
  'title' : IDL.Text,
  'isPosted' : IDL.Bool,
  'practiceArea' : Variant__1,
  'keywords' : IDL.Vec(IDL.Text),
  'timestamp' : Time,
  'trendRelevance' : Variant__2,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const SitemapEntry = IDL.Record({
  'loc' : IDL.Text,
  'changeFreq' : IDL.Opt(IDL.Text),
  'priority' : IDL.Opt(IDL.Nat),
  'lastMod' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addLegalListing' : IDL.Func([LegalListing], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createContactFormSubmission' : IDL.Func(
      [CreateContactFormSubmissionInput],
      [IDL.Nat],
      [],
    ),
  'createTrendingTopic' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, Variant__1, Variant__2],
      [IDL.Nat],
      [],
    ),
  'getAllContactFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getAllServices' : IDL.Func([], [IDL.Vec(ServiceDetails)], ['query']),
  'getAllTrendingTopics' : IDL.Func([], [IDL.Vec(TrendingTopic)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactFormSubmissionsByJurisdiction' : IDL.Func(
      [Variant__3],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getContactFormSubmissionsByStatus' : IDL.Func(
      [Variant],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getLegalDirectoryByJurisdiction' : IDL.Func(
      [Variant__3],
      [IDL.Vec(LegalListing)],
      ['query'],
    ),
  'getLegalDirectoryByJurisdictionAndPracticeArea' : IDL.Func(
      [Variant__3, Variant__1],
      [IDL.Vec(LegalListing)],
      ['query'],
    ),
  'getLegalDirectoryByPracticeArea' : IDL.Func(
      [Variant__1],
      [IDL.Vec(LegalListing)],
      ['query'],
    ),
  'getPostedTrendingTopics' : IDL.Func([], [IDL.Vec(TrendingTopic)], ['query']),
  'getServicesByJurisdiction' : IDL.Func(
      [Variant__3],
      [IDL.Vec(ServiceDetails)],
      ['query'],
    ),
  'getServicesByPracticeArea' : IDL.Func(
      [Variant__1],
      [IDL.Vec(ServiceDetails)],
      ['query'],
    ),
  'getSitemapEntries' : IDL.Func([], [IDL.Vec(SitemapEntry)], ['query']),
  'getTrendingTopicsByPracticeArea' : IDL.Func(
      [Variant__1],
      [IDL.Vec(TrendingTopic)],
      ['query'],
    ),
  'getTrendingTopicsByTrendRelevance' : IDL.Func(
      [Variant__2],
      [IDL.Vec(TrendingTopic)],
      ['query'],
    ),
  'getUnpostedTrendingTopics' : IDL.Func(
      [],
      [IDL.Vec(TrendingTopic)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isAdminActorFieldInitialized' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markTrendingTopicAsPosted' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateContactFormSubmissionStatus' : IDL.Func([IDL.Nat, Variant], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Variant__3 = IDL.Variant({
    'Secunderabad' : IDL.Null,
    'Cyberabad' : IDL.Null,
    'Rangareddy' : IDL.Null,
    'Hyderabad' : IDL.Null,
  });
  const Variant__1 = IDL.Variant({
    'startupLaw' : IDL.Null,
    'employmentLaw' : IDL.Null,
    'corporateLaw' : IDL.Null,
    'taxLaw' : IDL.Null,
    'documentationServices' : IDL.Null,
    'propertyLaw' : IDL.Null,
    'ipLaw' : IDL.Null,
    'civilLitigation' : IDL.Null,
    'criminalDefense' : IDL.Null,
    'familyLaw' : IDL.Null,
  });
  const LegalListing = IDL.Record({
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'jurisdiction' : Variant__3,
    'specialization' : Variant__1,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateContactFormSubmissionInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'jurisdiction' : Variant__3,
    'message' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Text,
  });
  const Variant__2 = IDL.Variant({ 'national' : IDL.Null, 'local' : IDL.Null });
  const Variant = IDL.Variant({
    'new' : IDL.Null,
    'resolved' : IDL.Null,
    'contacted' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactFormSubmission = IDL.Record({
    'id' : IDL.Nat,
    'status' : Variant,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'jurisdiction' : Variant__3,
    'message' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'phoneNumber' : IDL.Text,
  });
  const ServiceDetails = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'practiceArea' : Variant__1,
    'jurisdiction' : Variant__3,
    'keywords' : IDL.Vec(IDL.Text),
  });
  const TrendingTopic = IDL.Record({
    'id' : IDL.Nat,
    'popularityScore' : IDL.Nat,
    'title' : IDL.Text,
    'isPosted' : IDL.Bool,
    'practiceArea' : Variant__1,
    'keywords' : IDL.Vec(IDL.Text),
    'timestamp' : Time,
    'trendRelevance' : Variant__2,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const SitemapEntry = IDL.Record({
    'loc' : IDL.Text,
    'changeFreq' : IDL.Opt(IDL.Text),
    'priority' : IDL.Opt(IDL.Nat),
    'lastMod' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addLegalListing' : IDL.Func([LegalListing], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createContactFormSubmission' : IDL.Func(
        [CreateContactFormSubmissionInput],
        [IDL.Nat],
        [],
      ),
    'createTrendingTopic' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, Variant__1, Variant__2],
        [IDL.Nat],
        [],
      ),
    'getAllContactFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getAllServices' : IDL.Func([], [IDL.Vec(ServiceDetails)], ['query']),
    'getAllTrendingTopics' : IDL.Func([], [IDL.Vec(TrendingTopic)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactFormSubmissionsByJurisdiction' : IDL.Func(
        [Variant__3],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getContactFormSubmissionsByStatus' : IDL.Func(
        [Variant],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getLegalDirectoryByJurisdiction' : IDL.Func(
        [Variant__3],
        [IDL.Vec(LegalListing)],
        ['query'],
      ),
    'getLegalDirectoryByJurisdictionAndPracticeArea' : IDL.Func(
        [Variant__3, Variant__1],
        [IDL.Vec(LegalListing)],
        ['query'],
      ),
    'getLegalDirectoryByPracticeArea' : IDL.Func(
        [Variant__1],
        [IDL.Vec(LegalListing)],
        ['query'],
      ),
    'getPostedTrendingTopics' : IDL.Func(
        [],
        [IDL.Vec(TrendingTopic)],
        ['query'],
      ),
    'getServicesByJurisdiction' : IDL.Func(
        [Variant__3],
        [IDL.Vec(ServiceDetails)],
        ['query'],
      ),
    'getServicesByPracticeArea' : IDL.Func(
        [Variant__1],
        [IDL.Vec(ServiceDetails)],
        ['query'],
      ),
    'getSitemapEntries' : IDL.Func([], [IDL.Vec(SitemapEntry)], ['query']),
    'getTrendingTopicsByPracticeArea' : IDL.Func(
        [Variant__1],
        [IDL.Vec(TrendingTopic)],
        ['query'],
      ),
    'getTrendingTopicsByTrendRelevance' : IDL.Func(
        [Variant__2],
        [IDL.Vec(TrendingTopic)],
        ['query'],
      ),
    'getUnpostedTrendingTopics' : IDL.Func(
        [],
        [IDL.Vec(TrendingTopic)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isAdminActorFieldInitialized' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markTrendingTopicAsPosted' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateContactFormSubmissionStatus' : IDL.Func([IDL.Nat, Variant], [], []),
  });
};

export const init = ({ IDL }) => { return []; };