/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogArticle {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishedDate' : Time,
  'author' : string,
  'category' : Variant__1,
}
export interface ContactFormSubmission {
  'id' : bigint,
  'status' : Variant,
  'name' : string,
  'email' : string,
  'jurisdiction' : Variant__3,
  'message' : [] | [string],
  'timestamp' : Time,
  'phoneNumber' : string,
}
export interface CreateContactFormSubmissionInput {
  'name' : string,
  'email' : string,
  'jurisdiction' : Variant__3,
  'message' : [] | [string],
  'phoneNumber' : string,
}
export interface LegalListing {
  'contact' : string,
  'name' : string,
  'jurisdiction' : Variant__3,
  'specialization' : Variant__1,
}
export interface ServiceDetails {
  'title' : string,
  'description' : string,
  'practiceArea' : Variant__1,
  'jurisdiction' : Variant__3,
  'keywords' : Array<string>,
}
export interface SitemapEntry {
  'loc' : string,
  'changeFreq' : [] | [string],
  'priority' : [] | [bigint],
  'lastMod' : [] | [string],
}
export type Time = bigint;
export interface TrendingTopic {
  'id' : bigint,
  'popularityScore' : bigint,
  'title' : string,
  'isPosted' : boolean,
  'practiceArea' : Variant__1,
  'keywords' : Array<string>,
  'timestamp' : Time,
  'trendRelevance' : Variant__2,
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Variant = { 'new' : null } |
  { 'resolved' : null } |
  { 'contacted' : null };
export type Variant__1 = { 'startupLaw' : null } |
  { 'employmentLaw' : null } |
  { 'corporateLaw' : null } |
  { 'taxLaw' : null } |
  { 'documentationServices' : null } |
  { 'propertyLaw' : null } |
  { 'ipLaw' : null } |
  { 'civilLitigation' : null } |
  { 'criminalDefense' : null } |
  { 'familyLaw' : null };
export type Variant__2 = { 'national' : null } |
  { 'local' : null };
export type Variant__3 = { 'Secunderabad' : null } |
  { 'Cyberabad' : null } |
  { 'Rangareddy' : null } |
  { 'Hyderabad' : null };
export interface _SERVICE {
  'addLegalListing' : ActorMethod<[LegalListing], undefined>,
  'addOrUpdateBlogArticle' : ActorMethod<[BlogArticle], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createContactFormSubmission' : ActorMethod<
    [CreateContactFormSubmissionInput],
    bigint
  >,
  'createTrendingTopic' : ActorMethod<
    [string, Array<string>, bigint, Variant__1, Variant__2],
    bigint
  >,
  'getAllBlogArticles' : ActorMethod<[], Array<BlogArticle>>,
  'getAllContactFormSubmissions' : ActorMethod<
    [],
    Array<ContactFormSubmission>
  >,
  'getAllServices' : ActorMethod<[], Array<ServiceDetails>>,
  'getAllTrendingTopics' : ActorMethod<[], Array<TrendingTopic>>,
  'getBlogArticleById' : ActorMethod<[bigint], [] | [BlogArticle]>,
  'getBlogArticlesByCategory' : ActorMethod<[Variant__1], Array<BlogArticle>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactFormSubmissionsByJurisdiction' : ActorMethod<
    [Variant__3],
    Array<ContactFormSubmission>
  >,
  'getContactFormSubmissionsByStatus' : ActorMethod<
    [Variant],
    Array<ContactFormSubmission>
  >,
  'getLegalDirectoryByJurisdiction' : ActorMethod<
    [Variant__3],
    Array<LegalListing>
  >,
  'getLegalDirectoryByJurisdictionAndPracticeArea' : ActorMethod<
    [Variant__3, Variant__1],
    Array<LegalListing>
  >,
  'getLegalDirectoryByPracticeArea' : ActorMethod<
    [Variant__1],
    Array<LegalListing>
  >,
  'getPostedTrendingTopics' : ActorMethod<[], Array<TrendingTopic>>,
  'getServicesByJurisdiction' : ActorMethod<
    [Variant__3],
    Array<ServiceDetails>
  >,
  'getServicesByPracticeArea' : ActorMethod<
    [Variant__1],
    Array<ServiceDetails>
  >,
  'getSitemapEntries' : ActorMethod<[], Array<SitemapEntry>>,
  'getTrendingTopicsByPracticeArea' : ActorMethod<
    [Variant__1],
    Array<TrendingTopic>
  >,
  'getTrendingTopicsByTrendRelevance' : ActorMethod<
    [Variant__2],
    Array<TrendingTopic>
  >,
  'getUnpostedTrendingTopics' : ActorMethod<[], Array<TrendingTopic>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isAdminActorFieldInitialized' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markTrendingTopicAsPosted' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateContactFormSubmissionStatus' : ActorMethod<
    [bigint, Variant],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];